### ISSUE TITLE
Update to sonar-scanner-msbuild 2.3.1

### ISSUE THREAD

**Issue by pcoombe** [AgileArchitect/MSBuild.SonarQube.Runner.Tool#1]
Release Notes - SonarQube Scanner for MSBuild - Version 2.3.1
                                                            
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-315'>SONARMSBRU-315</a>] -         Update embedded Scanner CLI to the latest version
</li>
</ul>
                                            
        Release Notes - SonarQube Scanner for MSBuild - Version 2.3
            
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-199'>SONARMSBRU-199</a>] -         Analysis fails for valid Windows filenames, e.g. containing commas
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-228'>SONARMSBRU-228</a>] -         Pre-build fails if the analyzer name is too long
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-284'>SONARMSBRU-284</a>] -         Fail gracefully with old versions of the VB.NET plugin
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-288'>SONARMSBRU-288</a>] -         Projects built with MsBuild15 can&#39;t be analyzed
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-291'>SONARMSBRU-291</a>] -         Analysis of Visual Studio Solutions containing some C# source files using a non UTF-8 encoding fails
</li>
</ul>
                                                
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-44'>SONARMSBRU-44</a>] -         Show a nice usage summary if the MSBuild SonarQube Runner is not executed with the required arguments
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-140'>SONARMSBRU-140</a>] -         Colorise console output messages
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-159'>SONARMSBRU-159</a>] -         Exclude generated AssemblyAttributes.cs from the analysis
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-174'>SONARMSBRU-174</a>] -         Do not force the source encoding for every file to be UTF-8
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-224'>SONARMSBRU-224</a>] -         Shorten the paths within the &quot;.sonarqube\out\.sonar&quot; working folder
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-227'>SONARMSBRU-227</a>] -         Whenever an HTTP error occurs, the requested URL and response must be shown
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-246'>SONARMSBRU-246</a>] -         Scanner files are not removed when doing an MSBuild /t:clean
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-283'>SONARMSBRU-283</a>] -         Add a way to list all command line parameters
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-285'>SONARMSBRU-285</a>] -         Replace &#39;sonar.cs.msbuild.testProjectPattern&#39; with &#39;sonar.msbuild.testProjectPattern&#39; without default value
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-290'>SONARMSBRU-290</a>] -         Compute project level default encoding
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-292'>SONARMSBRU-292</a>] -         Default encoding should only be computed for C# and VB.NET projects
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-296'>SONARMSBRU-296</a>] -         Handle HTTP Unauthorized response from the server
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-300'>SONARMSBRU-300</a>] -         Increase timeout of coverage report conversion
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-301'>SONARMSBRU-301</a>] -         Replace use of /api/updatecenter/installed_plugins by /api/languages/list
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-302'>SONARMSBRU-302</a>] -         Replace use of /api/properties by /api/settings
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-305'>SONARMSBRU-305</a>] -         Make zipped distribution contains portable (forward) separators
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-306'>SONARMSBRU-306</a>] -         Populate sonar.sources for shared files on root module
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-307'>SONARMSBRU-307</a>] -         Honor SONARQUBE_SCANNER_PARAMS
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-309'>SONARMSBRU-309</a>] -         Support organizations
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-312'>SONARMSBRU-312</a>] -         Incorrect exit codes in begin and end steps
</li>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-313'>SONARMSBRU-313</a>] -         Make the paths under .sonarqube shorter
</li>
</ul>
        
<h2>        New Feature
</h2>
<ul>
<li>[<a href='https://jira.sonarsource.com/browse/SONARMSBRU-167'>SONARMSBRU-167</a>] -         Scanner for MSBuild must support .NET Core projects
</li>
</ul>

**Comment by tomstaijen** [comment]
solved
