### ISSUE TITLE
add newer release

### ISSUE THREAD

**Issue by jeremysimmons** [AgileArchitect/MSBuild.SonarQube.Runner.Tool#14]
[version 4.5.0.1761](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/4.5.0.1761) was released Dec 10, 2018. If you're open to a pull request, I'd be happy to submit a newer version so we can get this updated in nuget.

**Comment by guessmyname** [comment]
Version 4.6 was released on Feb 25. Would be great to get a new version. There are bug fixes in this release that I need.
